property1: app
property2: app

property.default: app

persons-list.persons:
  - firstName: John
    lastName: Smith
    age: 30
  - firstName: Tom
    lastName: Walker
    age: 40
  - firstName: Kate
    lastName: Hamilton
    age: 50
---
spring:
  config:
    activate:
      on-cloud-platform: "kubernetes"
property.activation: "I'm on Kubernetes!"